# Generated by Django 6.0.7 on 2026-08-01 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organizer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excels/')),
                ('name_x_percent', models.FloatField(default=50.0)),
                ('name_y_percent', models.FloatField(default=50.0)),
                ('font_size', models.PositiveIntegerField(default=48)),
                ('font_choice', models.CharField(choices=[('serif', 'Serif (Elegant)'), ('sans', 'Sans (Modern)'), ('script', 'Script (Handwritten)')], default='serif', max_length=30)),
                ('font_color', models.CharField(default='#1B2A4A', max_length=7)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('is_configured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cert_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='certificates.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
