# Generated by Django 6.0.7 on 2026-08-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_event_owner_event_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_quick_send',
            field=models.BooleanField(default=False, help_text='True if this event uses quick-send mode (add one person at a time)'),
        ),
    ]
